[package]
name = "quantic-fusion-mozilla-network"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[dependencies]
neqo-common = { git = "https://github.com/mozilla/neqo", tag = "v0.32.0", package = "neqo-common" }
neqo-http3 = { git = "https://github.com/mozilla/neqo", tag = "v0.32.0", package = "neqo-http3" }
neqo-transport = { git = "https://github.com/mozilla/neqo", tag = "v0.32.0", package = "neqo-transport" }
url = "2.5"
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs", "std", "tls12"] }
webpki-roots = "1"

nss = { version = "0.16.1", package = "nss-rs", path = "../../vendor/nss-rs" }

[patch."https://github.com/mozilla/nss-rs"]
nss-rs = { path = "../../vendor/nss-rs" }
