const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('quantic', {
  state: () => ipcRenderer.invoke('get-state'), onState: (fn) => ipcRenderer.on('browser-state', (_e, s) => fn(s)),
  navigate: (v) => ipcRenderer.invoke('navigate', v), prewarmSite: (u) => ipcRenderer.invoke('prewarm-site', u), chromeOverlay: (h) => ipcRenderer.invoke('chrome-overlay-height', h), newTab: (u) => u === undefined ? ipcRenderer.invoke('new-tab') : ipcRenderer.invoke('new-tab', u),
  activateTab: (id) => ipcRenderer.invoke('activate-tab', id), closeTab: (id) => ipcRenderer.invoke('close-tab', id),
  plusMenu: () => ipcRenderer.invoke('plus-menu'), mainMenu: () => ipcRenderer.invoke('main-menu'),
  searchEngineMenu: (x,y) => ipcRenderer.invoke('search-engine-menu',x,y),
  toggleRailCollapse: () => ipcRenderer.invoke('toggle-rail-collapse'),
  back: () => ipcRenderer.invoke('back'), forward: () => ipcRenderer.invoke('forward'), reload: () => ipcRenderer.invoke('reload'), stop: () => ipcRenderer.invoke('stop'),
  home: () => ipcRenderer.invoke('home'), toggleFavorite: () => ipcRenderer.invoke('toggle-favorite'), toggleAi: () => ipcRenderer.invoke('toggle-ai'),
  aiAction: (action, prompt='') => ipcRenderer.invoke('ai-action', action, prompt),
  careerStatus: () => ipcRenderer.invoke('career-status'),
  careerSettings: (patch={}) => ipcRenderer.invoke('career-settings', patch),
  careerRun: (options={}) => ipcRenderer.invoke('career-run', options),
  careerStop: () => ipcRenderer.invoke('career-stop'),
  careerFolder: () => ipcRenderer.invoke('career-folder'),
  careerOpenFolder: () => ipcRenderer.invoke('career-open-folder'),
  careerImport: () => ipcRenderer.invoke('career-import'),
  windowControl: (a) => ipcRenderer.invoke('window-control', a), chromeLock: (v) => ipcRenderer.invoke('set-chrome-lock', v),
  setSetting: (k,v) => ipcRenderer.invoke('set-setting', k, v), pickWallpaper: () => ipcRenderer.invoke('pick-wallpaper'), wallpaperData: () => ipcRenderer.invoke('wallpaper-data'), removeFavorite: (u) => ipcRenderer.invoke('remove-favorite', u),
  renameFavorite: (u,t) => ipcRenderer.invoke('rename-favorite', u,t), openDownloads: () => ipcRenderer.invoke('open-downloads'), retryVeil: () => ipcRenderer.invoke('retry-veil'), retryCurrent: () => ipcRenderer.invoke('retry-current'),
  extensionInstall: () => ipcRenderer.invoke('extension-install'),
  extensionRemove: (id) => ipcRenderer.invoke('extension-remove', id),
  syncExport: (passphrase) => ipcRenderer.invoke('sync-export', passphrase),
  syncImport: (passphrase) => ipcRenderer.invoke('sync-import', passphrase),
  onFocusAddress: (fn) => ipcRenderer.on('focus-address', fn), onFocusHomeSearch: (fn) => ipcRenderer.on('focus-home-search', fn)
});
